messages:
  unknownCommand: "%hataprefix%Hatalı bir komut girdiniz! Komutların listesi için &b/komutlar &cyazınız."
  disallowedName: "Güvenlik gerekçesiyle bu isimle giriş yapmak yasaktır."
  configReloaded: "%bilgiprefix%Yapılandırma yenilendi!"
  noPermission: "%hataprefix%Bunun için izniniz yok!"
  commandChatColorUsage: |
    &a--- Kullanabileceğiniz Renkler ---
    &f&l• &aYeşil, &bAçık_Mavi, &cAçık_Kırmızı, &dEflatun,
    &f&l• &eSarı, &fBeyaz, &0Siyah, &1Koyu_Mavi,
    &f&l• &2Koyu_Yeşil, &3Turkuaz, &4Koyu_Kırmızı, &5Koyu_Mor,
    &f&l• &6Turuncu, &7Gri, &8Koyu_Gri, &9Mavi
    &aÖrnek Kullanım: &b/renk Açık_Mavi
  commandChatColorWrongColor: "%hataprefix%Hatalı bir renk adı girdiniz!"
  commandChatColorSuccess: "%bilgiprefix%Konuşma renginiz %s olarak değiştirildi!"
  commandCommandsHeader: '&e--------------- &rKomutlar: sayfa %page%/%maxpage% &e---------------'
  commandCommandsNextPage: '&eBir sonraki sayfaya geçmek için &b/komutlar %page% &ekomutunu kullanın.'
  commandCommandsContent: # TODO
    - '&6/auction: &rAçık arttırma sisteminin ana komutudur.'
    - '&6/back: &rIşınlanmadan ya da ölmeden önceki konumunuza döndürür. (VIP ve UVIP)'
    - '&6/balance: &rPara miktarınızı gösterir.'
    - '&6/bid: &rAçık arttırmaya belirttiğiniz teklifi verir.'
    - '&6/challenges: &rSkyblock görevlerini gösterir.'
    - '&6/clearinventory: &rEnvanterinizi sıfırlar.'
    - '&6/ct: &rBir savaştaysanız kalan süreyi gösterir.'
    - '&6/duyuru: &rAda warpı reklamı gibi duyurularınızı yapabileceğiniz komut.'
  webInCombatDisabled: "%hataprefix%Savaş esnasında örümcek ağı koyamazsınız!"
  chatHover: |
    &aGönderme Zamanı: &b%time%
    &aPara: &b%vault_eco_balance_formatted%
    &a
    &aÖldürme/Ölme Oranı: &b%uniostats_kdr%
    &aGüç: &b%factionsuuid_player_power% 
commandInstances:
  "iteminfo": "itemdb"
  "elsat": "sell hand"
  "envsat": "sell inventory"
  "help": "komutlar"
  "kurallar": "rules"
  "kafa": "skull"
  "sandık": "pv"
  "chest": "pv"
  "kasa": "crates"
  "kasalar": "crates"
  "warp market": "market"
npcCommands:
  '0': bilgi